# Generated by Django 5.1.7 on 2025-03-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sprint",
            name="is_active",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
