# Generated by Django 5.1.4 on 2025-03-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="background",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
