# Generated by Django 5.1.7 on 2025-03-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_sprint_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("project", "name")},
        ),
    ]
